# Generated by Django 5.2.1 on 2025-05-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.URLField()),
                ('port', models.IntegerField(default=587)),
                ('host_user', models.CharField(max_length=255)),
                ('host_password', models.CharField(max_length=255)),
                ('use_tls', models.BooleanField(default=True)),
                ('from_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
